version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
     - /sonarr/data:/config
     - /plex/tvseries:/tv
     - /qbittorrent/downloads:/downloads
    ports:
     - 8989:8989
    restart: unless-stopped
